// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjihBKaXlGLON1sX1d33-f3CSXjP-XPWA',
    appId: '1:963272106482:android:a319c6029925a447470b6b',
    messagingSenderId: '963272106482',
    projectId: 'dodal-5d31c',
    storageBucket: 'dodal-5d31c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOZobfWx7OcDIQ0qDyq_AQxJeaeqiS_x0',
    appId: '1:963272106482:ios:24060dd3c2c74fc8470b6b',
    messagingSenderId: '963272106482',
    projectId: 'dodal-5d31c',
    storageBucket: 'dodal-5d31c.appspot.com',
    androidClientId: '963272106482-b4ofsg7q6lujll08161mlph5utmje828.apps.googleusercontent.com',
    iosClientId: '963272106482-fhc4cfiv8cjpet24ldcf1r405s2eigfn.apps.googleusercontent.com',
    iosBundleId: 'com.project.dodalApp',
  );
}
