# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :beta do |options|
    keychainName = 'ios-keychain'
    version = options[:version]
    password = options[:password]

    create_keychain(
      name: keychainName,
      password: password,
      unlock: true,
      timeout: 0,
      lock_when_sleeps: true,
    )
      
    match(
      git_url: "git@github.com:team-dodal/ios_certification.git",
      keychain_name: keychainName,
      keychain_password: password,
      type: "appstore",
      api_key_path: "app-store-api-key.json",
      readonly: true,
    )
    
    current_version_code = latest_testflight_build_number(
      api_key_path: "app-store-api-key.json",
    )
    build_number = current_version_code.to_i + 1
    sh("echo 'IOS_BUILD_NUMBER=#{build_number}' >> ../../deploy.history")
    
    gym(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      xcargs: "FLUTTER_BUILD_NAME='#{version}' FLUTTER_BUILD_NUMBER='#{build_number}'"
    )
      
    pilot(
      skip_waiting_for_build_processing: true,
      api_key_path: "app-store-api-key.json",
      app_version: version,
      distribute_external: true,
      groups: [
        "development"
      ]
    )
    delete_keychain(name: 'ios-keychain')
  end

  lane :release do |options|
    version = options[:version]
    password = options[:password]
    keychainName = 'ios-keychain'

    create_keychain(
      name: keychainName,
      password: password,
      unlock: true,
      timeout: 0,
      lock_when_sleeps: true,
    )
      
    match(
      git_url: "git@github.com:team-dodal/ios_certification.git",
      keychain_name: keychainName,
      keychain_password: password,
      type: "appstore",
      api_key_path: "app-store-api-key.json",
      readonly: true,
    )

    current_version_code = latest_testflight_build_number(
      api_key_path: "app-store-api-key.json",
    )
    build_number = current_version_code.to_i + 1

    gym(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      xcargs: "FLUTTER_BUILD_NAME='#{version}' FLUTTER_BUILD_NUMBER='#{build_number}'"
    )

    deliver(
      api_key_path: "app-store-api-key.json",
      app_version: version,
      skip_screenshots: true,
      skip_metadata: false,
      precheck_include_in_app_purchases: false,
      force: true, # 터미널 skip
      submit_for_review: true, # 올리자마자 심사
      automatic_release: true, # 심사하자마자 앱스토어 등록
      submission_information: {add_id_info_uses_idfa: false}
    )

    delete_keychain(name: 'ios-keychain')
  end
end
