# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :beta do |options|
    keychainName = 'ios-keychain'
    version = options[:version]
    password = options[:password]

    create_keychain(
      name: keychainName,
      password: password,
      unlock: true,
      timeout: 0,
      lock_when_sleeps: true,
    )
      
    match(
      git_url: "git@github.com:team-dodal/ios_certification.git",
      keychain_name: keychainName,
      keychain_password: password,
      type: "appstore",
      api_key_path: "app-store-api-key.json",
      readonly: true,
    )
    
    current_version_code = latest_testflight_build_number(
      api_key_path: "app-store-api-key.json",
    )
    build_number = current_version_code.to_i + 1
    sh("echo 'IOS_BUILD_NUMBER=#{build_number}' >> ../../deploy.history")
    
    gym(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      xcargs: "FLUTTER_BUILD_NAME='#{version}' FLUTTER_BUILD_NUMBER='#{build_number}'"
    )
      
    pilot(
      skip_waiting_for_build_processing: true,
      api_key_path: "app-store-api-key.json",
      app_version: version,
    )
    delete_keychain(name: 'ios-keychain')
  end

  lane :release do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end
end
