# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new beta build to Google Play"
  lane :beta do |options|
    version = options[:version]
    
    internal_code = google_play_track_version_codes(track: 'internal')
    production_code = google_play_track_version_codes(track: 'production')
    new_version_code = [internal_code[0], production_code[0]].max + 1
    
    sh("echo 'ANDROID_BUILD_NUMBER=#{new_version_code}' >> ../../deploy.history")
    gradle(
      task: "bundle",
      properties: {
        "versionCode" => new_version_code,
        "versionName" => version,
      }
    )
    supply(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :release do |options|
    version = options[:version]
    
    internal_code = google_play_track_version_codes(track: 'internal')
    production_code = google_play_track_version_codes(track: 'production')
    new_version_code = [internal_code[0], production_code[0]].max + 1
    
    gradle(
      task: "bundle",
      properties: {
        "versionCode" => new_version_code,
        "versionName" => version,
      }
    )
    supply(
      track: 'production',
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_apk: true,
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end
end
